version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_DB=lubricentro_myc
      - POSTGRES_USER=matiasadrian4
      - POSTGRES_PASSWORD=matiasadrian4
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=lubricentro_myc
      - DB_USER=matiasadrian4
      - DB_PASSWORD=matiasadrian4
      - DB_PORT=5432
    depends_on:
      - db
