# Generated by Django 2.2.3 on 2019-07-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lubricentro_myc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="desc1",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="producto",
            name="desc2",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="producto",
            name="desc3",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="producto",
            name="desc4",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
