# Generated by Django 2.2.3 on 2019-08-21 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lubricentro_myc', '0009_elementoremito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='elementoremito',
            name='numero_remito',
        ),
        migrations.AddField(
            model_name='elementoremito',
            name='remito',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lubricentro_myc.Remito'),
        ),
    ]
