# Generated by Django 2.2.3 on 2019-08-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lubricentro_myc", "0010_auto_20190821_0240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elementoremito",
            name="remito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lubricentro_myc.Remito"
            ),
        ),
    ]
