# Generated by Django 2.2.3 on 2019-08-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lubricentro_myc', '0012_remito_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lubricentro_myc.Cliente'),
        ),
    ]
