# Generated by Django 2.2.3 on 2019-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lubricentro_myc', '0013_auto_20190821_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoremito',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
