# Generated by Django 2.2.3 on 2019-08-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lubricentro_myc", "0015_auto_20190826_2356"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.FloatField()),
                ("precio_venta", models.FloatField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lubricentro_myc.Producto",
                    ),
                ),
            ],
        ),
    ]
