# Generated by Django 2.2.3 on 2019-08-28 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lubricentro_myc", "0016_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
