# Generated by Django 2.2.3 on 2019-08-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lubricentro_myc", "0017_venta_fecha"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venta",
            old_name="precio_venta",
            new_name="precio",
        ),
    ]
