# Generated by Django 2.2.7 on 2019-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lubricentro_myc', '0018_auto_20190828_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoremito',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
