# Generated by Django 2.2.7 on 2019-11-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lubricentro_myc', '0020_remove_elementoremito_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoremito',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
