# Generated by Django 4.0.4 on 2022-05-02 11:27

from django.db import migrations, models


def set_display_codes(apps, schema_editor):
    Producto = apps.get_model("lubricentro_myc", "Producto")
    for producto in Producto.objects.all():
        producto.codigo_en_pantalla = producto.codigo
        producto.save(update_fields=["codigo_en_pantalla"])


class Migration(migrations.Migration):

    dependencies = [
        ("lubricentro_myc", "0025_cliente_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="codigo_en_pantalla",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.RunPython(set_display_codes, migrations.RunPython.noop),
    ]
