# Generated by Django 4.1.1 on 2022-10-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lubricentro_myc", "0026_producto_codigo_en_pantalla_alter_producto_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCostHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.FloatField()),
                ("new_price", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lubricentro_myc.producto",
                    ),
                ),
            ],
        ),
    ]
