# Generated by Django 4.1.1 on 2022-11-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lubricentro_myc", "0027_productpricehistory"),
    ]

    operations = [
        migrations.RunSQL('ALTER SEQUENCE lubricentro_myc_producto_codigo_seq RESTART WITH 100000;')
    ]
