# Generated by Django 4.1.6 on 2023-03-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lubricentro_myc", "0028_auto_20221103_1135"),
    ]

    # This migration is only required when running an empty database.
    # For older databases coming from the legacy BE, this migration should be skipped.

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
