# Generated by Django 4.1.6 on 2024-04-04 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lubricentro_myc", "0029_alter_producto_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("info", "Info"),
                            ("unhandled_error", "Unhandled Exception"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
