# Generated by Django 4.1.6 on 2024-04-05 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lubricentro_myc", "0029_alter_producto_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("info", "Info"),
                            ("unhandled_exception", "Unhandled Exception"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
