# Generated by Django 4.1.6 on 2024-06-16 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lubricentro_myc", "0030_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSummaryItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("debe", "Debe"), ("haber", "Haber")], max_length=20
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lubricentro_myc.cliente",
                    ),
                ),
            ],
        ),
    ]
