/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Client
 */
export interface Client {
    /**
     * 
     * @type {number}
     * @memberof Client
     */
    codigo?: number;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    nombre: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    direccion?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    localidad?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    codigoPostal?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    telefono?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    cuit?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    email?: string;
}

export function ClientFromJSON(json: any): Client {
    return ClientFromJSONTyped(json, false);
}

export function ClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): Client {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'codigo': !exists(json, 'codigo') ? undefined : json['codigo'],
        'nombre': json['nombre'],
        'direccion': !exists(json, 'direccion') ? undefined : json['direccion'],
        'localidad': !exists(json, 'localidad') ? undefined : json['localidad'],
        'codigoPostal': !exists(json, 'codigo_postal') ? undefined : json['codigo_postal'],
        'telefono': !exists(json, 'telefono') ? undefined : json['telefono'],
        'cuit': !exists(json, 'cuit') ? undefined : json['cuit'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function ClientToJSON(value?: Client | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'codigo': value.codigo,
        'nombre': value.nombre,
        'direccion': value.direccion,
        'localidad': value.localidad,
        'codigo_postal': value.codigoPostal,
        'telefono': value.telefono,
        'cuit': value.cuit,
        'email': value.email,
    };
}

