/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    codigo?: number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    cliente?: number;
    /**
     * 
     * @type {Date}
     * @memberof Invoice
     */
    fecha?: Date;
}

export function InvoiceFromJSON(json: any): Invoice {
    return InvoiceFromJSONTyped(json, false);
}

export function InvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'codigo': !exists(json, 'codigo') ? undefined : json['codigo'],
        'cliente': !exists(json, 'cliente') ? undefined : json['cliente'],
        'fecha': !exists(json, 'fecha') ? undefined : (new Date(json['fecha'])),
    };
}

export function InvoiceToJSON(value?: Invoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'codigo': value.codigo,
        'cliente': value.cliente,
        'fecha': value.fecha === undefined ? undefined : (value.fecha.toISOString().substr(0,10)),
    };
}

