/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceItemQuantityList
 */
export interface InvoiceItemQuantityList {
    /**
     * 
     * @type {number}
     * @memberof InvoiceItemQuantityList
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InvoiceItemQuantityList
     */
    cantidad?: number;
}

export function InvoiceItemQuantityListFromJSON(json: any): InvoiceItemQuantityList {
    return InvoiceItemQuantityListFromJSONTyped(json, false);
}

export function InvoiceItemQuantityListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceItemQuantityList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'cantidad': !exists(json, 'cantidad') ? undefined : json['cantidad'],
    };
}

export function InvoiceItemQuantityListToJSON(value?: InvoiceItemQuantityList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'cantidad': value.cantidad,
    };
}

