/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InvoiceItemQuantityList,
    InvoiceItemQuantityListFromJSON,
    InvoiceItemQuantityListFromJSONTyped,
    InvoiceItemQuantityListToJSON,
} from './InvoiceItemQuantityList';

/**
 * 
 * @export
 * @interface InvoiceItemsQuantityList
 */
export interface InvoiceItemsQuantityList {
    /**
     * 
     * @type {Array<InvoiceItemQuantityList>}
     * @memberof InvoiceItemsQuantityList
     */
    elementos?: Array<InvoiceItemQuantityList>;
}

export function InvoiceItemsQuantityListFromJSON(json: any): InvoiceItemsQuantityList {
    return InvoiceItemsQuantityListFromJSONTyped(json, false);
}

export function InvoiceItemsQuantityListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceItemsQuantityList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elementos': !exists(json, 'elementos') ? undefined : ((json['elementos'] as Array<any>).map(InvoiceItemQuantityListFromJSON)),
    };
}

export function InvoiceItemsQuantityListToJSON(value?: InvoiceItemsQuantityList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elementos': value.elementos === undefined ? undefined : ((value.elementos as Array<any>).map(InvoiceItemQuantityListToJSON)),
    };
}

