/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InvoiceItem,
    InvoiceItemFromJSON,
    InvoiceItemFromJSONTyped,
    InvoiceItemToJSON,
} from './InvoiceItem';

/**
 * 
 * @export
 * @interface InvoiceItemsList
 */
export interface InvoiceItemsList {
    /**
     * 
     * @type {Array<InvoiceItem>}
     * @memberof InvoiceItemsList
     */
    elementos?: Array<InvoiceItem>;
}

export function InvoiceItemsListFromJSON(json: any): InvoiceItemsList {
    return InvoiceItemsListFromJSONTyped(json, false);
}

export function InvoiceItemsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceItemsList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elementos': !exists(json, 'elementos') ? undefined : ((json['elementos'] as Array<any>).map(InvoiceItemFromJSON)),
    };
}

export function InvoiceItemsListToJSON(value?: InvoiceItemsList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elementos': value.elementos === undefined ? undefined : ((value.elementos as Array<any>).map(InvoiceItemToJSON)),
    };
}

