/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceItem
 */
export interface InvoiceItem {
    /**
     * 
     * @type {number}
     * @memberof InvoiceItem
     */
    remito?: number;
    /**
     * 
     * @type {number}
     * @memberof InvoiceItem
     */
    producto?: number;
    /**
     * 
     * @type {number}
     * @memberof InvoiceItem
     */
    cantidad?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InvoiceItem
     */
    pagado?: boolean;
}

export function InvoiceItemFromJSON(json: any): InvoiceItem {
    return InvoiceItemFromJSONTyped(json, false);
}

export function InvoiceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'remito': !exists(json, 'remito') ? undefined : json['remito'],
        'producto': !exists(json, 'producto') ? undefined : json['producto'],
        'cantidad': !exists(json, 'cantidad') ? undefined : json['cantidad'],
        'pagado': !exists(json, 'pagado') ? undefined : json['pagado'],
    };
}

export function InvoiceItemToJSON(value?: InvoiceItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'remito': value.remito,
        'producto': value.producto,
        'cantidad': value.cantidad,
        'pagado': value.pagado,
    };
}

