/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceItemsIdsList
 */
export interface InvoiceItemsIdsList {
    /**
     * 
     * @type {Array<number>}
     * @memberof InvoiceItemsIdsList
     */
    elementos?: Array<number>;
}

export function InvoiceItemsIdsListFromJSON(json: any): InvoiceItemsIdsList {
    return InvoiceItemsIdsListFromJSONTyped(json, false);
}

export function InvoiceItemsIdsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceItemsIdsList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elementos': !exists(json, 'elementos') ? undefined : json['elementos'],
    };
}

export function InvoiceItemsIdsListToJSON(value?: InvoiceItemsIdsList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elementos': value.elementos,
    };
}

