/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductUpdateCostResult
 */
export interface ProductUpdateCostResult {
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateCostResult
     */
    resultado?: string;
}

export function ProductUpdateCostResultFromJSON(json: any): ProductUpdateCostResult {
    return ProductUpdateCostResultFromJSONTyped(json, false);
}

export function ProductUpdateCostResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUpdateCostResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resultado': !exists(json, 'resultado') ? undefined : json['resultado'],
    };
}

export function ProductUpdateCostResultToJSON(value?: ProductUpdateCostResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resultado': value.resultado,
    };
}

