/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    codigo?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    codigoEnPantalla?: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    detalle?: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    stock?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    precioCosto?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    desc1?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    desc2?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    desc3?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    desc4?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    flete?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    ganancia?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    iva?: number;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    agregadoCtaCte?: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    categoria?: string;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'codigo': !exists(json, 'codigo') ? undefined : json['codigo'],
        'codigoEnPantalla': !exists(json, 'codigo_en_pantalla') ? undefined : json['codigo_en_pantalla'],
        'detalle': !exists(json, 'detalle') ? undefined : json['detalle'],
        'stock': !exists(json, 'stock') ? undefined : json['stock'],
        'precioCosto': !exists(json, 'precio_costo') ? undefined : json['precio_costo'],
        'desc1': !exists(json, 'desc1') ? undefined : json['desc1'],
        'desc2': !exists(json, 'desc2') ? undefined : json['desc2'],
        'desc3': !exists(json, 'desc3') ? undefined : json['desc3'],
        'desc4': !exists(json, 'desc4') ? undefined : json['desc4'],
        'flete': !exists(json, 'flete') ? undefined : json['flete'],
        'ganancia': !exists(json, 'ganancia') ? undefined : json['ganancia'],
        'iva': !exists(json, 'iva') ? undefined : json['iva'],
        'agregadoCtaCte': !exists(json, 'agregado_cta_cte') ? undefined : json['agregado_cta_cte'],
        'categoria': !exists(json, 'categoria') ? undefined : json['categoria'],
    };
}

export function ProductToJSON(value?: Product | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'codigo': value.codigo,
        'codigo_en_pantalla': value.codigoEnPantalla,
        'detalle': value.detalle,
        'stock': value.stock,
        'precio_costo': value.precioCosto,
        'desc1': value.desc1,
        'desc2': value.desc2,
        'desc3': value.desc3,
        'desc4': value.desc4,
        'flete': value.flete,
        'ganancia': value.ganancia,
        'iva': value.iva,
        'agregado_cta_cte': value.agregadoCtaCte,
        'categoria': value.categoria,
    };
}

