/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Product,
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface ProductList
 */
export interface ProductList {
    /**
     * 
     * @type {Array<Product>}
     * @memberof ProductList
     */
    productos?: Array<Product>;
}

export function ProductListFromJSON(json: any): ProductList {
    return ProductListFromJSONTyped(json, false);
}

export function ProductListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productos': !exists(json, 'productos') ? undefined : ((json['productos'] as Array<any>).map(ProductFromJSON)),
    };
}

export function ProductListToJSON(value?: ProductList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productos': value.productos === undefined ? undefined : ((value.productos as Array<any>).map(ProductToJSON)),
    };
}

