/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Sale,
    SaleFromJSON,
    SaleFromJSONTyped,
    SaleToJSON,
} from './Sale';

/**
 * 
 * @export
 * @interface SaleList
 */
export interface SaleList {
    /**
     * 
     * @type {Array<Sale>}
     * @memberof SaleList
     */
    ventas?: Array<Sale>;
}

export function SaleListFromJSON(json: any): SaleList {
    return SaleListFromJSONTyped(json, false);
}

export function SaleListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ventas': !exists(json, 'ventas') ? undefined : ((json['ventas'] as Array<any>).map(SaleFromJSON)),
    };
}

export function SaleListToJSON(value?: SaleList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ventas': value.ventas === undefined ? undefined : ((value.ventas as Array<any>).map(SaleToJSON)),
    };
}

