/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sale
 */
export interface Sale {
    /**
     * 
     * @type {number}
     * @memberof Sale
     */
    producto?: number;
    /**
     * 
     * @type {number}
     * @memberof Sale
     */
    cantidad?: number;
    /**
     * 
     * @type {number}
     * @memberof Sale
     */
    precio?: number;
    /**
     * 
     * @type {Date}
     * @memberof Sale
     */
    fecha?: Date;
}

export function SaleFromJSON(json: any): Sale {
    return SaleFromJSONTyped(json, false);
}

export function SaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sale {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'producto': !exists(json, 'producto') ? undefined : json['producto'],
        'cantidad': !exists(json, 'cantidad') ? undefined : json['cantidad'],
        'precio': !exists(json, 'precio') ? undefined : json['precio'],
        'fecha': !exists(json, 'fecha') ? undefined : (new Date(json['fecha'])),
    };
}

export function SaleToJSON(value?: Sale | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'producto': value.producto,
        'cantidad': value.cantidad,
        'precio': value.precio,
        'fecha': value.fecha === undefined ? undefined : (value.fecha.toISOString().substr(0,10)),
    };
}

