/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SalesPerMonth
 */
export interface SalesPerMonth {
    /**
     * 
     * @type {Array<number>}
     * @memberof SalesPerMonth
     */
    salesPerMonth?: Array<number>;
}

export function SalesPerMonthFromJSON(json: any): SalesPerMonth {
    return SalesPerMonthFromJSONTyped(json, false);
}

export function SalesPerMonthFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesPerMonth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'salesPerMonth': !exists(json, 'sales_per_month') ? undefined : json['sales_per_month'],
    };
}

export function SalesPerMonthToJSON(value?: SalesPerMonth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sales_per_month': value.salesPerMonth,
    };
}

