/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimplifiedClient
 */
export interface SimplifiedClient {
    /**
     * 
     * @type {number}
     * @memberof SimplifiedClient
     */
    codigo?: number;
    /**
     * 
     * @type {string}
     * @memberof SimplifiedClient
     */
    nombre?: string;
}

export function SimplifiedClientFromJSON(json: any): SimplifiedClient {
    return SimplifiedClientFromJSONTyped(json, false);
}

export function SimplifiedClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimplifiedClient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'codigo': !exists(json, 'codigo') ? undefined : json['codigo'],
        'nombre': !exists(json, 'nombre') ? undefined : json['nombre'],
    };
}

export function SimplifiedClientToJSON(value?: SimplifiedClient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'codigo': value.codigo,
        'nombre': value.nombre,
    };
}

