/* tslint:disable */
/* eslint-disable */
/**
 * Lubricentro M&C
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: matiasadrianpp4@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GenerarStockPdfGetRequest {
    categoria: string;
}

/**
 * 
 */
export class FileActionsApi extends runtime.BaseAPI {

    /**
     * Get a PDF containing the products stock for a given category
     */
    async generarStockPdfGetRaw(requestParameters: GenerarStockPdfGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.categoria === null || requestParameters.categoria === undefined) {
            throw new runtime.RequiredError('categoria','Required parameter requestParameters.categoria was null or undefined when calling generarStockPdfGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.categoria !== undefined) {
            queryParameters['categoria'] = requestParameters.categoria;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/generar_stock_pdf`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a PDF containing the products stock for a given category
     */
    async generarStockPdfGet(requestParameters: GenerarStockPdfGetRequest, initOverrides?: RequestInit): Promise<void> {
        await this.generarStockPdfGetRaw(requestParameters, initOverrides);
    }

}
