name: Django CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: matiasadrian4
          POSTGRES_USER: matiasadrian4
          POSTGRES_DB: lubricentro_myc
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django_project/requirements.txt
      - name: Run Tests
        run: python django_project/manage.py test lubricentro_myc
